### ISSUE TITLE
Failed to resolve import "./create-recipe.mjs" from "styled-system/recipes/tooltip.mjs"

### ISSUE THREAD

**Issue by gabrielgrant** [cschroeter/park-ui#115]
I've added PandaCSS, Ark and Park to a React project, and added a simple Heading component to test, but getting the following error when trying to use it (same error appeared with Accordion component, but thought I'd try simplifying things by just trying Heading to start):

```
[plugin:vite:import-analysis] Failed to resolve import "./create-recipe.mjs" from "styled-system/recipes/tooltip.mjs". Does the file exist?
/.../styled-system/recipes/tooltip.mjs:2:31
1  |  import { splitProps, getSlotCompoundVariant } from '../helpers.mjs';
2  |  import { createRecipe } from './create-recipe.mjs';
   |                                ^
3  |  
4  |  const tooltipDefaultVariants = {}
    at formatError (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:63045:46)
    at TransformContext.error (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:63039:19)
    at normalizeUrl (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:61320:33)
    at async file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:61470:47
    at async Promise.all (index 1)
    at async TransformContext.transform (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:61391:13)
    at async Object.transform (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:63340:30)
    at async loadAndTransform (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:49083:29)
    at async viteTransformMiddleware (file:///.../node_modules/vite/dist/node/chunks/dep-wTaJK0Jt.js:58681:32
```

App.tsx
```
import { Heading } from './components/park/Heading'


function App() {

  return (
    <>
      <Heading>Hello</Heading>
    </>
  )
}

export default App
```

**Comment by gabrielgrant** [comment]
not sure how/why this happened, but removing the styled-system dir and regenerating seemed to fix it

```
$ rm -r styled-system/
$ npx panda codegen
```

I do have the prepare script set up in package.json:
```
"scripts": {
    ...
    "prepare": "panda codegen"
  },
```

Leaving this open in case there is some manual step needed in the docs to avoid this (or if there is some step that I just missed?)

**Comment by cschroeter** [comment]
@gabrielgrant 

Thanks for taking your time to create this issue. Looks like this is an issue with Panda CSS itself. As a long time user I can say that clearing the `styled-system` folder is always a good starting point when something goes wrong - especially when updating to a newer version.

With time this should get more stable and solid. Thanks for documenting this.
