### ISSUE TITLE
Cannot read properties of undefined (reading 'match') when using `createPreset`

### ISSUE THREAD

**Issue by mac-codes9** [cschroeter/park-ui#228]
I'm guessing it's something to do with the setting of the colour.  Everything works fine if I just use: `'@park-ui/panda-preset'` however the customisation would be useful! 

```
import { defineConfig } from "@pandacss/dev";
import { createPreset } from "@park-ui/panda-preset";

export default defineConfig({
  preflight: true,
  presets: [
    "@pandacss/preset-base",
    createPreset({
      accentColor: "crimson",
      grayColor: "neutral",
      borderRadius: "2xl",
    }),
  ],
  include: ["./app/*.{js,jsx,ts,tsx}"],
  exclude: [],
  theme: {
    extend: {},
  },
  outdir: "styled-system",
});
```

## Next.js Error

```
warn [config] ⚠️ Invalid config:
- [tokens]: Missing token: `colors.crimson.9` used in `config.semanticTokens.colors.accent.default`
- [tokens]: Missing token: `colors.crimson.10` used in `config.semanticTokens.colors.accent.emphasized`
- [tokens]: Missing token: `colors.crimson.a11` used in `config.semanticTokens.colors.accent.text`
```

## Full Error

From running `panda studio --verbose`

```
🐼 error [cli] CACError: Unknown option `--verbose`
    at Command.checkUnknownOptions (/Users/mac/Documents/way2ravey/node_modules/cac/dist/index.js:404:17)
    at CAC.runMatchedCommand (/Users/mac/Documents/way2ravey/node_modules/cac/dist/index.js:602:13)
    at main (/Users/mac/Documents/way2ravey/node_modules/@pandacss/dev/dist/cli-default.js:18929:15)
    at Object.<anonymous> (/Users/mac/Documents/way2ravey/node_modules/@pandacss/dev/dist/cli-default.js:18941:1)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
error: "panda" exited with code 1
```

## Also While I'm Here

your docs site is amazing, two pointers. It would be great if you included an API reference alongside each component not just examples of different usages, kinda like Radix UI Themes does (see screenshot).
<img width="837" alt="Screenshot 2024-02-09 at 12 58 49" src="https://github.com/cschroeter/park-ui/assets/115668288/d20cba2e-ee1c-4f24-bd6d-1e450f13dd77">

The other point is when copying code a copy code button would be great, however the click and drag selection in code blocks isn't visible at all.

**Comment by TunkShif** [comment]
After upgrading `@park-ui/panda-preset` from `0.31.0` to `0.34.0`, I got the same problem when setting custom gray color and accent color.

```
🐼 warn [config] ⚠️ Invalid config:
- [tokens]: Missing token: `colors.sage.9` used in `config.semanticTokens.colors.gray.default`
- [tokens]: Missing token: `colors.sage.10` used in `config.semanticTokens.colors.gray.emphasized`
- [tokens]: Missing token: `colors.sage.12` used in `config.semanticTokens.colors.gray.text`
- [tokens]: Missing token: `colors.tomato.9` used in `config.semanticTokens.colors.accent.default`
- [tokens]: Missing token: `colors.tomato.10` used in `config.semanticTokens.colors.accent.emphasized`
- [tokens]: Missing token: `colors.tomato.a11` used in `config.semanticTokens.colors.accent.text`
```

My guess is that the color token generation process went wrong, so some tokens are missing as reported above. I tried to inspect the output of `defineColorTokens()` function in https://github.com/cschroeter/park-ui/blob/main/plugins/panda/src/theme/tokens/colors.ts#L5C14-L5C31 , but it seems to look totally fine. 🤔

**Comment by cschroeter** [comment]
@TunkShif 

I've introduced a new `additionalColors` option in the `createPreset` function to decrease the CSS bundle size effectively. By default, the preset includes only the `gray` and `accent` colors. 
This maybe a breaking change for some users, so please update your configuration accordingly.

Example configuration:

```tsx
import { defineConfig } from '@pandacss/dev';
import { createPreset } from '@park-ui/panda-preset';

export default defineConfig({
  presets: [
    '@pandacss/preset-base',
    createPreset({
      accentColor: 'amber',
      grayColor: 'sand',
      additionalColors: ['red', 'green'],
    }),
  ],
  // Additional configuration...
})
```

To add all available colors (like previous), use this wildcard:

```tsx
createPreset({
  additionalColors: ['*'],
}),
```

**Comment by mac-codes9** [comment]
@cschroeter that worked, thank you. I did try setting the additional colours however just added red and green like it the example which still caused errors with crimson accent colours missing. So if I want to use certain colours I.e crimson I need to make sure to set `accent: 'crimson'` and also ensure `additionalColors` includes crimson.

**Comment by cschroeter** [comment]
@mac-codes9 

You should not have to add `crimson` to the `additionalColors` field  if you have declared `crimson` as your accent color.

Your config should look like this and `crimson` should be available:

```
import { defineConfig } from '@pandacss/dev';
import { createPreset } from '@park-ui/panda-preset';

export default defineConfig({
  presets: [
    '@pandacss/preset-base',
    createPreset({
      accentColor: 'crimson',
      // additionalColors: ['crimson'], <-- if you have to do that, than pls reopen
    }),
  ],
  // Additional configuration...
})

**Comment by TunkShif** [comment]
@cschroeter I'm getting this error if I only set the `grayColor` and `accentColor` option

```
🐼 warn [config] ⚠️ Invalid config:
- [tokens]: Missing token: `colors.sage.9` used in `config.semanticTokens.colors.gray.default`
- [tokens]: Missing token: `colors.sage.10` used in `config.semanticTokens.colors.gray.emphasized`
- [tokens]: Missing token: `colors.sage.12` used in `config.semanticTokens.colors.gray.text`
- [tokens]: Missing token: `colors.tomato.9` used in `config.semanticTokens.colors.accent.default`
- [tokens]: Missing token: `colors.tomato.10` used in `config.semanticTokens.colors.accent.emphasized`
- [tokens]: Missing token: `colors.tomato.a11` used in `config.semanticTokens.colors.accent.text`
```

```ts
import { defineConfig } from '@pandacss/dev';
import { createPreset } from '@park-ui/panda-preset';

export default defineConfig({
  presets: [
    '@pandacss/preset-base',
    createPreset({
      accentColor: 'tomato',
      grayColor: 'sage'
    }),
  ]
})
```

But if I add the corresponding accent color and gray color to the `additionalColors` option, then it works.

```ts
export default defineConfig({
  presets: [
    '@pandacss/preset-base',
    createPreset({
      accentColor: 'tomato',
      grayColor: 'sage',
      additionalColors: ['sage', 'tomato']
    }),
  ]
})

```

**Comment by mac-codes9** [comment]
> @mac-codes9
> 
> You should not have to add `crimson` to the `additionalColors` field if you have declared `crimson` as your accent color.
> 
> Your config should look like this and `crimson` should be available:
> 
> ```tsx
> import { defineConfig } from '@pandacss/dev';
> import { createPreset } from '@park-ui/panda-preset';
> 
> export default defineConfig({
>   presets: [
>     '@pandacss/preset-base',
>     createPreset({
>       accentColor: 'crimson',
>       // additionalColors: ['crimson'], <-- if you have to do this, please re-open the issue
>     }),
>   ],
> })
> ```

See I thought this and that's what my original issue was about, it works fine if I have `additionalColors: ['*']`

Otherwise
```🐼 warn [config] ⚠️ Invalid config:
- [tokens]: Missing token: `colors.crimson.9` used in `config.semanticTokens.colors.accent.default`
- [tokens]: Missing token: `colors.crimson.10` used in `config.semanticTokens.colors.accent.emphasized`
- [tokens]: Missing token: `colors.crimson.a11` used in `config.semanticTokens.colors.accent.text`
```

With configuration:
```
import { defineConfig } from "@pandacss/dev";
import { createPreset } from '@park-ui/panda-preset'

export default defineConfig({
  preflight: true,
  presets: [
      '@pandacss/preset-base',
      createPreset({
        accentColor: 'crimson',
        grayColor: 'neutral',
    }),
  ],
  include: ["./app/**/*.{js,jsx,ts,tsx}"],
  exclude: [],
  jsxFramework: "react",
  outdir: "styled-system",
});
```

**Comment by lee-reinhardt** [comment]
Chiming in to say I ran into this yesterday too after updating.

My `accentColor` and `grayColor` were not automatically included. I had to redundantly list them in the `additionalColors` array.

This config

```js
export default defineConfig({
  preflight: true,
  presets: [
    '@pandacss/preset-base',
    createPreset({
      grayColor: 'slate',
      accentColor: 'indigo',
      borderRadius: 'sm'
    })
  ],
  include: ['./src/**/*.{js,jsx,ts,tsx}'],
  exclude: [],
  jsxFramework: 'react',
  outdir: 'styled-system',
  theme: { ... },
  staticCss: { ... }
})
```

results in these errors

```
 ○ Compiling / ...
🐼 warn [config] ⚠️ Invalid config:
- [tokens]: Missing token: `colors.slate.9` used in `config.semanticTokens.colors.gray.default`
- [tokens]: Missing token: `colors.slate.10` used in `config.semanticTokens.colors.gray.emphasized`
- [tokens]: Missing token: `colors.slate.12` used in `config.semanticTokens.colors.gray.text`
- [tokens]: Missing token: `colors.indigo.9` used in `config.semanticTokens.colors.accent.default`
- [tokens]: Missing token: `colors.indigo.10` used in `config.semanticTokens.colors.accent.emphasized`
- [tokens]: Missing token: `colors.indigo.a11` used in `config.semanticTokens.colors.accent.text`
```

Adding them fixes it.
```
additionalColors: ['slate', 'indigo'],
```


```
"@ark-ui/react": "2.0.2",
"@pandacss/dev": "0.30.2",
"@park-ui/panda-preset": "0.34.0",
```
