### ISSUE TITLE
Dialog error : "Cannot read properties of undefined (reading 'splitVariantProps')"

### ISSUE THREAD

**Issue by vincehi** [cschroeter/park-ui#468]
When I want to use the Dialog I get an error
<img width="869" alt="Capture d’écran 2024-11-13 à 11 46 06" src="https://github.com/user-attachments/assets/ce5b18ca-d039-48c7-841f-ee17ee858cc1">
```
TypeError: Cannot read properties of undefined (reading 'splitVariantProps')
    at StyledComponent (create-style-context.tsx:22:49)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at get children [as children] (index.tsx?pick=default&pick=$css:57:63)
    at Object.get [as children] (/usr/src/app/node_modules/solid-js/dist/server.js:389:28)
    at Object.get [as children] (/usr/src/app/node_modules/solid-js/dist/server.js:389:28)
    at Object.get [as children] (/usr/src/app/node_modules/solid-js/dist/server.js:389:28)
    at ssrElement (/usr/src/app/node_modules/solid-js/web/dist/server.js:861:69)
    at Dynamic (/usr/src/app/node_modules/solid-js/web/dist/server.js:1142:14)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at StyledComponent (factory.mjs:99:34)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at Container (:3000/usr/src/app/styled-system/jsx/container.mjs:19:30)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at Home (index.tsx?pick=default&pick=$css:31:32)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at Promise.Comp [as resolved] (:3000/usr/src/app/node_modules/@solidjs/start/dist/router/lazyRoute.js:35:107)
    at wrap (/usr/src/app/node_modules/solid-js/dist/server.js:614:30)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at Object.outlet (:3000/usr/src/app/node_modules/@solidjs/router/dist/routing.js:456:53)
    at get children [as children] (components.jsx:138:23)
    at /usr/src/app/node_modules/solid-js/dist/server.js:216:35
    at /usr/src/app/node_modules/solid-js/dist/server.js:179:49
    at createMemo (/usr/src/app/node_modules/solid-js/dist/server.js:95:9)
    at children (/usr/src/app/node_modules/solid-js/dist/server.js:179:16)
    at /usr/src/app/node_modules/solid-js/dist/server.js:216:14
    at createMemo (/usr/src/app/node_modules/solid-js/dist/server.js:95:9)
    at provider (/usr/src/app/node_modules/solid-js/dist/server.js:211:12)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at children (components.jsx:135:49)
    at Show (/usr/src/app/node_modules/solid-js/dist/server.js:435:9)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at eval (components.jsx:130:38)
    at Routes (components.jsx:127:51)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at get children [as children] (components.jsx:36:95)
    at get children [as children] (components.jsx:75:22)
    at get children [as children] (app.tsx:28:101)
    at get children [as children] (client.jsx:101:20)
    at /usr/src/app/node_modules/solid-js/dist/server.js:216:35
    at /usr/src/app/node_modules/solid-js/dist/server.js:179:49
    at createMemo (/usr/src/app/node_modules/solid-js/dist/server.js:95:9)
    at children (/usr/src/app/node_modules/solid-js/dist/server.js:179:16)
    at /usr/src/app/node_modules/solid-js/dist/server.js:216:14
    at createMemo (/usr/src/app/node_modules/solid-js/dist/server.js:95:9)
    at provider (/usr/src/app/node_modules/solid-js/dist/server.js:211:12)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at SessionProvider (client.jsx:95:32)
    at Module.createComponent (/usr/src/app/node_modules/solid-js/dist/server.js:367:15)
    at get children [as children] (app.tsx:25:38)
    at /usr/src/app/node_modules/solid-js/dist/server.js:701:41
    ```

**Comment by vincehi** [comment]
my bad, it's me
